### ISSUE TITLE
Error when launching MSFragger-GUI

### ISSUE THREAD

**Issue by ot0tot** [chhh/FragPipe#67]
# Describe the problem

* **I'm submitting a:**
  - [x] problem running the software
  - [x] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

When launching MSFragger GUI v6.0, the following appears in the terminal window used to launch it:
```
$ java -jar MSFragger-GUI.jar 
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1626)
	at umich.msfragger.gui.MsfraggerGuiFrame.validateMsfraggerVersion(MsfraggerGuiFrame.java:2105)
	at umich.msfragger.gui.MsfraggerGuiFrame.validateAndSaveMsfraggerPath(MsfraggerGuiFrame.java:1759)
	at umich.msfragger.gui.MsfraggerGuiFrame.access$200(MsfraggerGuiFrame.java:148)
	at umich.msfragger.gui.MsfraggerGuiFrame$4.run(MsfraggerGuiFrame.java:333)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

## System info

You can find that printed on the _Config_ tab.
- OS and version: **Ubuntu 16.04 LTS amd64**
- Java version: ** java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)**

----

## Describe your experiment

N/A - error happens when launching GUI
Note: MSFragger GUI seems to run correctly despite the above error.

**Comment by chhh** [comment]
We haven't tested Java 10, only  7, 8 and 9.
This is a non-issue, it's just one library function that I used to check the actual running java version, and it looks like this function is broken under Java 10 (like many other things).

Thanks for reporting, I'll fix that!

**Comment by chhh** [comment]
should have been fixed in later versions
