### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ot0tot** [chhh/FragPipe#69]
# Describe the problem

* **I'm submitting a:**
  - [x] problem running the software
  - [x] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [x] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

# Describe the problem

 **"Index out of range" error before run is completed**
Using the MSFragger/FragPipe issue reporting template as I'm getting the error while running MSFragger-GUI, but I get the same error when I run philosopher from the command line. Tested on both an Ubuntu and Windows machine with the same error. Some information redacted with "xxx".

## System info

You can find that printed on the _Config_ tab.
- OS and version: **Ubuntu 16.04 LTS amd64**
- Java version: **java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)**

----

### General proteomics experiment description
Mouse polyclonal antibodies digested with trypsin

### Input data files
1 mzML file ~150 Mb in size

### Sequence database

**UP000001811 with custom V region sequences and decoys**  
**45 Mb**

----

## Attach fragger.params file

```
num_threads = 0			# 0=poll CPU to set num threads; else specify num threads directly (max 64)
precursor_mass_tolerance = 500.00
precursor_mass_lower = -100			# Overrides the lower bound of the window set by precursor_mass_tolerance
precursor_mass_upper = 100			# Overrides the upper bound of the window set by precursor_mass_tolerance
precursor_mass_units = 1			# 0=Daltons, 1=ppm
precursor_true_tolerance = 20
precursor_true_units = 1			# 0=Daltons, 1=ppm
fragment_mass_tolerance = 20
fragment_mass_units = 1			# 0=Daltons, 1=ppm
isotope_error = 0/1/2			# 0=off, -1/0/1/2/3 (standard C13 error)
mass_offsets = 0			# allow for additional precursor mass window shifts. Multiplexed with isotope_error. mass_offsets = 0/79.966 can be used as a restricted ‘open’ search that looks for unmodified and phosphorylated peptides (on any residue)
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2			# 2 for enzymatic, 1 for semi-enzymatic, 0 for nonspecific digestion
allowed_missed_cleavage = 1			# maximum value is 5
clip_nTerm_M = 1
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
# variable_mod_03 = 79.96633 STY
# variable_mod_04 = -17.02650 nQnC
# variable_mod_05 = -18.01060 nE
allow_multiple_variable_mods_on_residue = 1			# static mods are not considered
max_variable_mods_per_mod = 3			# maximum of 5
max_variable_mods_combinations = 5000			# maximum of 65534, limits number of modified peptides generated from sequence
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
precursor_charge = 0 0			# precursor charge range to analyze; does not override any existing charge; 0 as 1st entry ignores parameter
override_charge = 0			# 0=no, 1=yes to override existing precursor charge states with precursor_charge parameter
digest_min_length = 7
digest_max_length = 50
digest_mass_range = 500.0 5000.0			# MH+ peptide mass range to analyze
max_fragment_charge = 2			# set maximum fragment charge state to analyze (allowed max 5)
track_zero_topN = 0			# in addition to topN results, keep track of top results in zero bin
zero_bin_accept_expect = 0			# boost top zero bin entry to top if it has expect under 0.01 - set to 0 to disable
zero_bin_mult_expect = 1			# disabled if above passes - multiply expect of zero bin for ordering purposes (does not affect reported expect)
add_topN_complementary = 0
minimum_peaks = 15			# required minimum number of peaks in spectrum to search (default 10)
use_topN_peaks = 100
min_fragments_modelling = 3
min_matched_fragments = 4
minimum_ratio = 0.01			# filter peaks below this fraction of strongest peak
clear_mz_range = 0.0 0.0			# for iTRAQ/TMT type data; will clear out all peaks in the specified m/z range
add_Cterm_peptide = 0.000000
add_Nterm_peptide = 0.000000
add_Cterm_protein = 0.000000
add_Nterm_protein = 0.000000
add_G_glycine = 0.000000
add_A_alanine = 0.000000
add_S_serine = 0.000000
add_P_proline = 0.000000
add_V_valine = 0.000000
add_T_threonine = 0.000000
add_C_cysteine = 57.021464
add_L_leucine = 0.000000
add_I_isoleucine = 0.000000
add_N_asparagine = 0.000000
add_D_aspartic_acid = 0.000000
add_Q_glutamine = 0.000000
add_K_lysine = 0.000000
add_E_glutamic_acid = 0.000000
add_M_methionine = 0.000000
add_H_histidine = 0.000000
add_F_phenylalanine = 0.000000
add_R_arginine = 0.000000
add_Y_tyrosine = 0.000000
add_W_tryptophan = 0.000000
add_B_user_amino_acid = 0.000000
add_J_user_amino_acid = 0.000000
add_O_user_amino_acid = 0.000000
add_U_user_amino_acid = 0.000000
add_X_user_amino_acid = 0.000000
add_Z_user_amino_acid = 0.000000
database_name = /home/xxx/xxx/run1/2018-06-22-td-2018-06-22-td-UP000001811.fas
```

## Run log output

```
System info:
System OS: Linux, Architecture: amd64
Java Info: 10.0.1, Java HotSpot(TM) 64-Bit Server VM, "Oracle Corporation"

Version info:
MSFragger-GUI version 6.0
MSFragger version 20180223-RC1
Philosopher version Philosopher 20180530

Will execute 9 commands:
java -jar /home/xxx/xxx/msfragger-20180223-RC1.one-jar.jar /home/xxx/xxx/run1/result/fragger.params /home/xxx/xxx/run1/QExxxxx-LUMOS.mzML 

java -cp /home/xxx/xxx/run1/MSFragger-GUI.jar umich.msfragger.util.FileMove /home/xxx/xxx/run1/QExxxxx-LUMOS.pepXML /home/xxx/xxx/run1/result/QExxxxx-LUMOS.pepXML 

/home/xxx/xxx/philosopher_linux_amd64 workspace --clean 

/home/xxx/xxx/philosopher_linux_amd64 workspace --init 

/home/xxx/xxx/philosopher_linux_amd64 peptideprophet --decoy rev_ --decoyprobs --ppm --accmass --nonparam --expectscore --database /home/xxx/xxx/run1/2018-06-22-td-2018-06-22-td-UP000001811.fas /home/xxx/xxx/run1/result/QExxxxx-LUMOS.pepXML 

/home/xxx/xxx/philosopher_linux_amd64 proteinprophet --output interact interact-QExxxxx-LUMOS.pep.xml 

/home/xxx/xxx/philosopher_linux_amd64 database --annotate /home/xxx/xxx/run1/2018-06-22-td-2018-06-22-td-UP000001811.fas --prefix rev_ 

/home/xxx/xxx/philosopher_linux_amd64 filter --sequential --tag rev_ --pepxml /home/xxx/xxx/run1/result --protxml /home/xxx/xxx/run1/result/interact.prot.xml 

/home/xxx/xxx/philosopher_linux_amd64 report 

~~~~~~~~~~~~~~~~~~~~~~


Executing command:
$> java -jar /home/xxx/xxx/msfragger-20180223-RC1.one-jar.jar /home/xxx/xxx/run1/result/fragger.params /home/xxx/xxx/run1/QExxxxx-LUMOS.mzML 
Process started
MSFragger version MSFragger-20180223
(c) University of Michigan

System OS: Linux, Architecture: amd64
Java Info: 10.0.1, Java HotSpot(TM) 64-Bit Server VM, "Oracle Corporation"
JVM started with 4004MB memory


Peptide index read in 224ms
Selected fragment tolerance 0.10 Da and maximum fragment slice size of 2342.79MB

344352420 fragments to be searched in 2 slices (2.57GB total)
Operating on slice 1 of 2: 
4907ms
	QExxxxx-LUMOS.mzML 
3697ms

	QExxxxx-LUMOS.mzML 3697ms [progress: 21404/21404 (100.00%) - 6302.71 spectra/s] - completed 3517ms

Operating on slice 2 of 2: 
4189ms
	QExxxxx-LUMOS.mzML 
2093ms

	QExxxxx-LUMOS.mzML 2093ms [progress: 21404/21404 (100.00%) - 14212.48 spectra/s]
 - completed 1609ms

Process finished, exit value: 0
Executing command:
$> java -cp /home/xxx/xxx/run1/MSFragger-GUI.jar umich.msfragger.util.FileMove /home/xxx/xxx/run1/QExxxxx-LUMOS.pepXML /home/xxx/xxx/run1/result/QExxxxx-LUMOS.pepXML 
Process started
Process finished, exit value: 0
Executing command:
$> /home/xxx/xxx/philosopher_linux_amd64 workspace --clean 
Process started
time="20:43:55" level=info msg="Executing Workspace 20180530"

time="20:43:56" level=info msg="Removing workspace"

time="20:43:56" level=info msg=Done

Process finished, exit value: 0
Executing command:
$> /home/xxx/xxx/philosopher_linux_amd64 workspace --init 
Process started
time="20:43:56" level=info msg="Executing Workspace 20180530"

time="20:43:57" level=info msg="Creating workspace"

time="20:43:57" level=info msg=Done

Process finished, exit value: 0
Executing command:
$> /home/xxx/xxx/philosopher_linux_amd64 peptideprophet --decoy rev_ --decoyprobs --ppm --accmass --nonparam --expectscore --database /home/xxx/xxx/run1/2018-06-22-td-2018-06-22-td-UP000001811.fas /home/xxx/xxx/run1/result/QExxxxx-LUMOS.pepXML 
Process started
time="20:43:57" level=info msg="Executing PeptideProphet 20180530"

 file 1: /home/xxx/xxx/run1/result/QExxxxx-LUMOS.pepXML

 processed altogether 17740 results

INFO: Results written to file: /home/xxx/xxx/run1/result/interact-QExxxxx-LUMOS.pep.xml


  - /home/xxx/xxx/run1/result/interact-QExxxxx-LUMOS.pep.xml

  - Building Commentz-Walter keyword tree...

  - Searching the tree...
  - Linking duplicate entries...
  - Printing results...

using Accurate Mass Bins
using PPM mass difference
Using Decoy Label "rev_".
Decoy Probabilities will be reported.
Using non-parametric distributions
 (X! Tandem) (using Tandem's expectation score for modeling)

adding ACCMASS mixture distribution
init with X! Tandem trypsin 

 PeptideProphet  (TPP v5.0.1 Post-Typhoon dev, Build 201705191541-exported (Linux-x86_64)) AKeller@ISB
 read in 0 1+, 5344 2+, 8881 3+, 2958 4+, 508 5+, 49 6+, and 0 7+ spectra.
Found 8023 Decoys, and 9717 Non-Decoys

MS Instrument info: Manufacturer: UNKNOWN, Model: UNKNOWN, Ionization: UNKNOWN, Analyzer: UNKNOWN, Detector: UNKNOWN

INFO: Processing standard MixtureModel ... 
Initialising statistical models ...

Iterations: .
.
.
.
.
.
.
.
.
10
.
.
.
.
.
.
.
.
.
20
.
.
.
.
.
.
.
WARNING: Mixture model quality test failed for charge (1+).



WARNING: Mixture model quality test failed for charge (7+).

model complete after 28 iterations

time="20:44:40" level=info msg=Done

Process finished, exit value: 0
Executing command:
$> /home/xxx/xxx/philosopher_linux_amd64 proteinprophet --output interact interact-QExxxxx-LUMOS.pep.xml 
Process started
time="20:44:40" level=info msg="Executing ProteinProphet 20180530"

ProteinProphet (C++) by Insilicos LLC and LabKey Software, after the original Perl by A. Keller (TPP v5.0.1 Post-Typhoon dev, Build 201705221614-exported (Linux-x86_64))
 (no FPKM) (using degen pep info)
Reading in /home/xxx/xxx/run1/result/interact-QExxxxx-LUMOS.pep.xml...

...read in 0 1+, 1318 2+, 897 3+, 324 4+, 90 5+, 5 6+, 0 7+ spectra with min prob 0.05


Initializing 867 peptide weights: 0%...10%
...20%...30%...40%...50%
...60%...70%...80%...90%...100%
Calculating protein lengths and molecular weights from database /home/xxx/xxx/run1/2018-06-22-td-2018-06-22-td-UP000001811.fas
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........1000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........2000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........3000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........4000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........5000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........6000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........7000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........8000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........9000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........10000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........11000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........12000

.........:.........:.........:.........:.........:.........:.........:.........:.........:.........13000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........14000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........15000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........16000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........17000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........18000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........19000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........20000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........21000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........22000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........23000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........24000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........25000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........26000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........27000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........28000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........29000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........30000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........31000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........32000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........33000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........34000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........35000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........36000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........37000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........38000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........39000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........40000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........41000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........42000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........43000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........44000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........45000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........46000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........47000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........48000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........49000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........50000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........51000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........52000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........53000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........54000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........55000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........56000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........57000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........58000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........59000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........60000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........61000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........62000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........63000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........64000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........65000

.........:.........:.........:.........:.........:.........:.........:.........:.........:.........66000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........67000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........68000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........69000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........70000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........71000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........72000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........73000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........74000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........75000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........76000

.........:.........:.........:.........:.........:.........:.........:.........:.........:.........77000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........78000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........79000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........80000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........81000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........82000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........83000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........84000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........85000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........86000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........87000

.........:.........:.........:.........:.........:.........:.........:.........:.........:.........88000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........89000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........90000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........91000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........92000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........93000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........94000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........95000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........96000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........97000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........98000

.........:.........:.........:.........:.........:.........:.........:.........:.........:.........99000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........100000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........101000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........102000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........103000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........104000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........105000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........106000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........107000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........108000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........109000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........110000

.........:.........:.........:.........:.........:.........:.........:.........:.........:.........111000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........112000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........113000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........114000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........115000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........116000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........117000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........118000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........119000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........120000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........121000

.........:.........:.........:.........:.........:.........:.........:.........:.........:.........122000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........123000
.........:.........:.........:.........:.........:.........:.........:.........:.........:.........124000
.........:.........:.........:.........:.........  Total: 124495

Computing degenerate peptides for 22908 proteins: 0%...10%
...20%
...30%
...40%
...50%
...60%
...70%...80%...90%
...100%

Computing probabilities for 23550 proteins.  Loop 1: 0%...20%...40%
...60%...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%

Computing probabilities for 23550 proteins.  Loop 1: 0%...20%...40%
...60%...80%
...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 23550 proteins.  Loop 1: 0%...20%
...40%...60%
...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%

Computing probabilities for 23550 proteins.  Loop 1: 0%...20%...40%...60%
...80%...100%  Loop 2: 0%...20%...40%...60%...80%...100%

Computing probabilities for 23550 proteins.  Loop 1: 0%...20%...40%
...60%...80%
...100%  Loop 2: 0%...20%...40%...60%...80%...100%
Computing probabilities for 23550 proteins.  Loop 1: 0%...20%
...40%...60%...80%
...100%  Loop 2: 0%...20%...40%...60%...80%...100%

Computing 1099 protein groups: 0%...10%
...20%
...30%
...40%
...50%
...60%
...70%
...80%
...90%
...100%
Calculating sensitivity...
and error tables...


INFO: mu=3.73252e-06, db_size=72619408

Computing MU for 23550 proteins: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%


Finished

time="20:48:44" level=info msg=Done

Process finished, exit value: 0
Executing command:
$> /home/xxx/xxx/philosopher_linux_amd64 database --annotate /home/xxx/xxx/run1/2018-06-22-td-2018-06-22-td-UP000001811.fas --prefix rev_ 
Process started
time="20:48:44" level=info msg="Executing Database 20180530"
time="20:48:44" level=info msg="Processing database"

time="20:49:12" level=info msg=Done

Process finished, exit value: 0
Executing command:
$> /home/xxx/xxx/philosopher_linux_amd64 filter --sequential --tag rev_ --pepxml /home/xxx/xxx/run1/result --protxml /home/xxx/xxx/run1/result/interact.prot.xml 
Process started
time="20:49:12" level=info msg="Executing Filter 20180530"
time="20:49:12" level=info msg="Processing peptide identification files"

time="20:49:20" level=info msg="1+ Charge profile" decoy=0 target=0
time="20:49:20" level=info msg="2+ Charge profile" decoy=448 target=967
time="20:49:20" level=info msg="3+ Charge profile" decoy=347 target=616
time="20:49:20" level=info msg="4+ Charge profile" decoy=143 target=187
time="20:49:20" level=info msg="5+ Charge profile" decoy=39 target=51
time="20:49:20" level=info msg="6+ Charge profile" decoy=2 target=3
time="20:49:20" level=info msg="Database search results" ions=941 peptides=826 psms=2803
time="20:49:20" level=info msg="Converged to 0.00 % FDR with 0 PSMs" decoy=0 threshold=10 total=0
time="20:49:20" level=info msg="Converged to 0.00 % FDR with 0 Peptides" decoy=0 threshold=10 total=0
time="20:49:20" level=info msg="Converged to 0.00 % FDR with 0 Ions" decoy=0 threshold=10 total=0

time="20:50:21" level=info msg="Protein inference results" decoy=526 target=573
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/prvst/philosopher/lib/fil.ProtXMLFilter(0x0, 0x0, 0x7ffdbb78d0e9, 0x4, 0xc43e3aca00, 0x130, 0x220, 0x0, 0x0, 0x3f847ae147ae147b, ...)
	/home/felipevl/go/src/github.com/prvst/philosopher/lib/fil/fil.go:1763 +0x1d46
github.com/prvst/philosopher/lib/fil.processProteinIdentifications(0x0, 0x0, 0x7ffdbb78d0e9, 0x4, 0xc43e3aca00, 0x130, 0x220, 0x0, 0x0, 0x3f847ae147ae147b, ...)
	/home/felipevl/go/src/github.com/prvst/philosopher/lib/fil/fil.go:572 +0x319
github.com/prvst/philosopher/lib/fil.Run(0xc420028750, 0x24, 0xc420024980, 0x1b, 0xc420028780, 0x29, 0xc4200287b0, 0x2a, 0xc4200287e0, 0x21, ...)
	/home/felipevl/go/src/github.com/prvst/philosopher/lib/fil/fil.go:53 +0xd44
github.com/prvst/philosopher/cmd.glob..func5(0x3c90900, 0xc420186460, 0x0, 0x7)
	/home/felipevl/go/src/github.com/prvst/philosopher/cmd/filter.go:53 +0x200
github.com/spf13/cobra.(*Command).execute(0x3c90900, 0xc4201863f0, 0x7, 0x7, 0x3c90900, 0xc4201863f0)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/spf13/cobra.(*Command).ExecuteC(0x3c92580, 0x3c926d0, 0xc420175f78, 0x405a4c)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:852 +0x30a
github.com/spf13/cobra.(*Command).Execute(0x3c92580, 0x1, 0x0)
	/home/felipevl/go/src/github.com/spf13/cobra/command.go:800 +0x2b
github.com/prvst/philosopher/cmd.Execute()
	/home/felipevl/go/src/github.com/prvst/philosopher/cmd/root.go:32 +0x2d
main.main()
	/home/felipevl/go/src/github.com/prvst/philosopher/main.go:19 +0x70

Process finished, exit value: 2
Previous process returned exit code [2], cancelling further processing..
Cancelled execution of: 
/home/xxx/xxx/philosopher_linux_amd64 report 
=========================
===
===        Done
===
=========================
```
[https://github.com/prvst/philosopher/issues/22](url)

**Comment by prvst** [comment]
@ot0tot 

I noticed that your database is named `2018-06-22-td-2018-06-22-td-UP000001811.fas`, did you ran the database command twice ? Can you share the file with me ?

**Comment by ot0tot** [comment]
This is solved. MSConverter was not fully converting the raw files, leaving me with a truncated mzML file. 
Re-installing MSConverter solved the issue and generated full 1+ Gb mzML files, and the above runs without error.
