### ISSUE TITLE
Not able to run with decoy database

### ISSUE THREAD

**Issue by YousufAKhan** [chhh/FragPipe#73]
# Describe the problem

Hey! I generated my human fasta database by getting all the protein sequences from uniprot (~200 mb, ~500,000 sequences) + common contaminants. I then create a reverse decoy database and combined it with my human fasta database (~400 mb, ~1,000,000 entries). However, whenever I try run MSFragger, I routinely encounter issues with Java saying that there is not enough heap space, yet I am running it with an allotted 8GB ram (I only have up to 8GB of physical DDR3 ram + a i7-4700HQ). I have attached my log sheet below. 

I am able to get through a full run (using the same HEK293 database from the original MSFragger publication) without concatenating the decoy database, but this doesn't allow for the identification of any proteins in my protXML file! 

* **I'm submitting a:**
  - [ x] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [x ] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **

Issue with using concatenated FASTA file

## System info

Windows 10

You can find that printed on the _Config_ tab.
- OS and version: Windows 10 (AMD64)
- Java version: 1.80_161
----

## Describe your experiment

Repeating the analysis done in the original MSFragger paper with the same dataset

### Genral proteomics experiment description
e.g. "_TMT, Human, full cell lysate with Trypsin_" , "_AP-MS pulldowns, mouse,
liver tissue_"

...

### Input data files
** e.g. "_fractionated HeLa, 5 samples, 3 bio replicates, 2 technical replicates_" or "_ten 3 hour LC gradients, full cell lysate, fruit fly_" or
or at least "_5 mzml files 1.5Gb each_" **

All 24 files from the dataset, roughly ~1.5gb each

### Sequence database

Human uniprot (~200mb) + reverse decoy (~200 mb)

** _your response here, preferably a link or at least name, organism etc._ **  
** _Size of the either in proteins or in megabytes_ **

----

## Attach fragger.params file

num_threads = 8
precursor_mass_tolerance = 500.00
precursor_mass_lower = -100
precursor_mass_upper = 100
precursor_mass_units = 1
precursor_true_tolerance = 20
precursor_true_units = 1
fragment_mass_tolerance = 20
fragment_mass_units = 1
isotope_error = 0/1/2
mass_offsets = 0
search_enzyme_name = Trypsin
search_enzyme_cutafter = KR
search_enzyme_butnotafter = P
num_enzyme_termini = 2
allowed_missed_cleavage = 1
clip_nTerm_M = 1
variable_mod_01 = 15.99490 M
variable_mod_02 = 42.01060 [^
# variable_mod_03 = 79.96633 STY
# variable_mod_04 = -17.02650 nQnC
# variable_mod_05 = -18.01060 nE
allow_multiple_variable_mods_on_residue = 1
max_variable_mods_per_mod = 3
max_variable_mods_combinations = 5000
output_file_extension = pepXML
output_format = pepXML
output_report_topN = 1
output_max_expect = 50.0
precursor_charge = 0 0
override_charge = 0
digest_min_length = 7
digest_max_length = 50
digest_mass_range = 500.0 5000.0
max_fragment_charge = 2
track_zero_topN = 0
zero_bin_accept_expect = 0
zero_bin_mult_expect = 1
add_topN_complementary = 0
minimum_peaks = 15
use_topN_peaks = 100
min_fragments_modelling = 3
min_matched_fragments = 4
minimum_ratio = 0.01
clear_mz_range = 0.0 0.0
add_Cterm_peptide = 0.000000
add_Nterm_peptide = 0.000000
add_Cterm_protein = 0.000000
add_Nterm_protein = 0.000000
add_G_glycine = 0.000000
add_A_alanine = 0.000000
add_S_serine = 0.000000
add_P_proline = 0.000000
add_V_valine = 0.000000
add_T_threonine = 0.000000
add_C_cysteine = 57.021464
add_L_leucine = 0.000000
add_I_isoleucine = 0.000000
add_N_asparagine = 0.000000
add_D_aspartic_acid = 0.000000
add_Q_glutamine = 0.000000
add_K_lysine = 0.000000
add_E_glutamic_acid = 0.000000
add_M_methionine = 0.000000
add_H_histidine = 0.000000
add_F_phenylalanine = 0.000000
add_R_arginine = 0.000000
add_Y_tyrosine = 0.000000
add_W_tryptophan = 0.000000
add_B_user_amino_acid = 0.000000
add_J_user_amino_acid = 0.000000
add_O_user_amino_acid = 0.000000
add_U_user_amino_acid = 0.000000
add_X_user_amino_acid = 0.000000
add_Z_user_amino_acid = 0.000000
database_name = E:\MSFragger-20171106\Databases\combinedwithdecoy.fasta

## Run log output

```
System info:
System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_161, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation

Version info:
FragPipe version 7.1
MSFragger version 20180316
Philosopher version 20180808 (build 201808081133)

Will execute 9 commands:
java -jar -Xmx8G E:\MSFragger-20171106\MSFragger-20180316_dup_6632361882206306053.jar E:\MSFragger-20171106\Output\HEK293 decoy\fragger.params E:\MSFragger-20171106\HEK293 mass spec\b1906_293T_proteinID_01A_QE3_122212.mzXML 

java -cp E:\MSFragger-20171106\FragPipe.exe umich.msfragger.util.FileMove E:\MSFragger-20171106\HEK293 mass spec\b1906_293T_proteinID_01A_QE3_122212.pepXML E:\MSFragger-20171106\Output\HEK293 decoy\b1906_293T_proteinID_01A_QE3_122212.pepXML 

E:\MSFragger-20171106\philosopher_windows_amd64.exe workspace --clean 

E:\MSFragger-20171106\philosopher_windows_amd64.exe workspace --init 

E:\MSFragger-20171106\philosopher_windows_amd64.exe peptideprophet --decoy XXX_ --decoyprobs --ppm --accmass --nonparam --expectscore --database E:\MSFragger-20171106\Databases\combinedwithdecoy.fasta E:\MSFragger-20171106\Output\HEK293 decoy\b1906_293T_proteinID_01A_QE3_122212.pepXML 

E:\MSFragger-20171106\philosopher_windows_amd64.exe proteinprophet --output interact interact-b1906_293T_proteinID_01A_QE3_122212.pep.xml 

E:\MSFragger-20171106\philosopher_windows_amd64.exe database --annotate E:\MSFragger-20171106\Databases\combinedwithdecoy.fasta --prefix XXX_ 

E:\MSFragger-20171106\philosopher_windows_amd64.exe filter --sequential --tag XXX_ --pepxml E:\MSFragger-20171106\Output\HEK293 decoy --protxml E:\MSFragger-20171106\Output\HEK293 decoy\interact.prot.xml 

E:\MSFragger-20171106\philosopher_windows_amd64.exe report 

~~~~~~~~~~~~~~~~~~~~~~


Executing command:
$> java -jar -Xmx8G E:\MSFragger-20171106\MSFragger-20180316_dup_6632361882206306053.jar E:\MSFragger-20171106\Output\HEK293 decoy\fragger.params E:\MSFragger-20171106\HEK293 mass spec\b1906_293T_proteinID_01A_QE3_122212.mzXML 
Process started
MSFragger version MSFragger-20180316
MSFTBX version 1.8.2
(c) University of Michigan

System OS: Windows 10, Architecture: AMD64
Java Info: 1.8.0_161, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
JVM started with 7282MB memory


Peptide index read in 13229ms
Selected fragment tolerance 0.10 Da and maximum fragment slice size of 4496.04MB

4340311304 fragments to be searched in 8 slices (32.34GB total)
Operating on slice 1 of 8: 
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at edu.umich.andykong.msfragger.e.a(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more

```

**Comment by YousufAKhan** [comment]
You cannot begin to imagine how stupid I feel right NOW! Thank you so much.
