### ISSUE TITLE
Launch MSFragger in Linux without GUI

### ISSUE THREAD

**Issue by lisujun** [chhh/FragPipe#79]
# Describe the problem

* **I'm submitting a:
  - [ X ] problem running the software
  - [ ] bug report
  - [ ] feature request
  - [ ] question

* **My MSFragger use case:**
  - [ ] _Closed_ search (standard small precursor mass tolerance)
  - [ ] _Open_ search (large precursor mass tolerance)

 ** _put your general problem description here_ **
Exception in thread "AWT-EventQueue-0" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:207)
        at java.awt.Window.<init>(Window.java:535)
        at java.awt.Frame.<init>(Frame.java:420)
        at java.awt.Frame.<init>(Frame.java:385)
        at javax.swing.JFrame.<init>(JFrame.java:174)
        at umich.msfragger.gui.MsfraggerGuiFrame.<init>(MsfraggerGuiFrame.java:189)
        at umich.msfragger.gui.MsfraggerGuiFrame$73.run(MsfraggerGuiFrame.java:5281)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:218)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:133)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:122)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:118)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:110)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

My question is that if we run under linux environment, do you have some options to turn off the GUI that we could write in the command line for the parameters ?

**Comment by chhh** [comment]
@lisujun Sure, FragPipe is a UI that launches a bunch of other programs. MSfragger is a java jar file. You can launch it from the command line, you will need java 8 for that. `java -jar <path-to-msfragger.jar>` to just "launch" the jar file. You will need to create a parameters file as well, but you can reuse one that was created by FragPipe during your previous searches, it's saved to the output directory. FragPipe also has a button on the MSFragger tab to save a parameters file to a custom location (according to the current form state). 
You can also run FragPipe on a machine with a display attached, unlike the linux environment you used (that's what `HeadlessException` means - it needed a monitor to display the gui), set up the search, and before clicking RUN, check the `Dry run` checkbox. It will only show the equivalent command line commands to be executed. As a matter of fact you can just copy-paste those commands into a terminal and it should work. In that terminal `cd` to the "output directory" before running.

Hope this helps,
Dmitry

**Comment by chhh** [comment]
no response, closing
